### ISSUE TITLE
Cannot open files in sidebar

### ISSUE THREAD

**Issue by jpinnix** [lukakerr/twig#30] opened 2019-02-13 20:11 UTC
Clicking on a file in the sidebar, whether on the top level or inside a folder, does not open the file.

<img width="208" alt="screen shot 2019-02-13 at 2 05 44 pm" src="https://user-images.githubusercontent.com/4436/52740557-dfee9480-2f98-11e9-911c-3bca1cd424f4.png">

**Comment by zollero** [comment] 2019-02-15 06:46
The file name with Chinese characters can not be opened too.
![image](https://user-images.githubusercontent.com/8801894/52839274-7a351080-3130-11e9-966c-1970c25a4c03.png)

**Comment by lukakerr** [comment] 2019-02-18 00:50
I believe this has now been fixed in ff6e548. Filenames with spaces or unicode weren't being decoded properly, and now should be.

If you still experience this problem after the next release, feel free to re-open this issue.

**Closed by lukakerr** 2019-02-18 00:50 UTC
Labels: bug

**Comment by lorenzofanchi** [comment] 2019-10-17 07:35
When I select a file from the sidebar, the file appears "Locked". When I try to save, I'm presented with the prompt "This file cannot be found". However, the file is still in its original location and the filename has not changed.

**Comment by lukakerr** [comment] 2019-10-17 08:28
I can't reproduce the folders with spaces issue (see below), but can reproduce the locked issue. I will take a look and make a fix.

<img width="203" alt="Screen Shot 2019-10-17 at 7 27 33 pm" src="https://user-images.githubusercontent.com/20056300/66991626-2ee65e00-f114-11e9-84a9-d479d462de22.png">

**Comment by lorenzofanchi** [comment] 2019-10-17 09:57
here's an example of a folder structure where 'folder with spaces' does not appear.

[toplevel.zip](https://github.com/lukakerr/Pine/files/3738582/toplevel.zip)
